# https://circleci.com/docs/2.0/language-php/
# https://circleci.com/docs/2.0/circleci-images/
version: 2

php70_defaults: &php70_defaults
    working_directory: '~/project'
    docker:
        - image: 'circleci/php:7.0'

php71_defaults: &php71_defaults
    working_directory: '~/project'
    docker:
        - image: 'circleci/php:7.1'

php72_defaults: &php72_defaults
    working_directory: '~/project'
    docker:
        - image: 'circleci/php:7.1'

attach_workspace: &attach_workspace
    attach_workspace:
        at: '.'

persist_workspace: &persist_workspace
    persist_to_workspace:
        root: '.'
        paths: [ '.' ]

workflows:

    version: 2

    pipeline:
        jobs:
            - fetch_code
            - install_php_dependencies:
                requires: [ fetch_code ]

            - static_analysis:
                requires: [ install_php_dependencies ]
            - linting:
                requires: [ install_php_dependencies ]

            - unit_tests_70:
                requires: [ linting ]

            - unit_tests_71:
                requires: [ linting ]

            - unit_tests_72:
                requires: [ linting ]

jobs:
    fetch_code:
        <<: *php72_defaults
        steps:
            - checkout
            - *persist_workspace

    install_php_dependencies:
        <<: *php72_defaults
        steps:
            - *attach_workspace

            - restore_cache:
                keys: [ 'v1-php-deps-{{ checksum "composer.lock" }}', 'v1-php-deps' ]

            - run:
                name: 'Install PHP dependencies'
                command: |
                    composer --no-interaction --no-progress install
                    composer show

            - save_cache:
                key: 'v1-php-deps-{{ checksum "composer.lock" }}'
                paths: [ 'vendor' ]

            - *persist_workspace

    static_analysis:
        <<: *php72_defaults
        steps:
            - *attach_workspace
            - run:
                name: 'Run static analysis'
                command: |
                    vendor/bin/phpstan analyse \
                    -l 2 \
                    --memory-limit=1G \
                    src

    linting:
        <<: *php72_defaults
        steps:
            - *attach_workspace

            - run:
                name: 'Run syntax check'
                command: 'vendor/bin/phplint --no-cache --ansi src'

            - run:
                name: 'Run code formatting check'
                command: 'vendor/bin/phpcs -n --colors src'

    unit_tests_70:
        <<: *php70_defaults
        steps:
            - *attach_workspace
            - run:
                name: 'Run unit tests'
                command: 'phpdbg -qrr vendor/bin/phpunit'

    unit_tests_71:
        <<: *php71_defaults
        steps:
            - *attach_workspace
            - run:
                name: 'Run unit tests'
                command: 'phpdbg -qrr vendor/bin/phpunit'

    unit_tests_72:
        <<: *php72_defaults
        steps:
            - *attach_workspace
            - run:
                name: 'Run unit tests'
                command: 'phpdbg -qrr vendor/bin/phpunit'
            - store_test_results:
                path: '.phpunit/report'
